---
title: "Est_Unspoken_v1.6"
output: html_document
editor_options: 
  chunk_output_type: console
chunk_output_type: console
---
*CODE FOR ANALYZING UNSPOKEN DATA: ATTRACTION, CONVERSION AND COMBINED*
  Run each step by clicking on arrow at far right
  Results in subfolder (prefix_date-GMT) of HOME/UNSPOKEN created
  Zip file also created which can be downloaded by clicking on it

########################################## 
## 1. LOAD PACKAGES & GET DATA via SHINY
```{r Load Packages and Data}
library(sqldf)
library(readxl) # Read excel
library(cmdstanr) # Interface to Stan
library(posterior) # Process Stan draws
library(doParallel); library(parallel) # R Multi-threading for EB
library(shiny)
source("https://raw.githubusercontent.com/klattery/Estimation-Ecosystem/master/EE_Functions_Stan4.1.R")
#source("https://raw.githubusercontent.com/klattery/Estimation-Ecosystem/master/Stan_RShiny_UI.R")
dir <- list(work = "/home/rstudio/Unspoken", # output and other work
            stanmodel = "/home/rstudio/Unspoken/StanCode" # code for Stan Model
)
source("https://raw.githubusercontent.com/klattery/Unspoken/master/UnspokenEst_GetData_RShiny.R")
shinyApp(env_shiny$ui_unspoken1, env_shiny$server_unspoken1)
```

########################################## 
## 2. ESTIMATE UTILITIES
```{r Estimate}
# Basic default specs
conv_cols <- list( # Specify the column numbers of choice_data for each of the inputs below
  id = 1,  # respondent id
  task = 3, # task number
  dep = 6, # 0 = Not swiped, 1 = swiped
  time = 7, # time (usually in milliseconds but will be standardized anyway)
  atts = 4 # ind vars that we want to estimate utilities for
)
att_cols <- list(
  id = 1,
  task = 3,
  dep = 5, 
  time = 6,  
  atts = 4
)
# Initial attraction dep data -> recodes:
# 0 ?     ->  0,
# 1 Left  -> -1,
# 2 Right ->  1,
# 3 Heart ->  2,
# 4 Cross -> -1,
# 5 Tick  ->  1
att_recode <- c(0, -1, 1, 2, -1, 1)
data_model <- list(
  iter_warmup = 400, # warmup of 400 is plenty
  iter_sampling = 400, # sampling of 400 is plenty
  df = 2,              # recommend df = 2 for Inverse Wishart
  prior_cov_scale = 1, # default 1
  export_draws = FALSE, # True will export draws to output directory
  scale_bounds = c(.6, 1), # Bounds on utility scale: attraction * scale = conversion 
  wts_bound_att = c(.1, 1.9), # Bounds on attraction task/time weights
  wts_bound_conv = c(.1, 1.9) # Bounds on conversion task/time weights
)
source("https://raw.githubusercontent.com/klattery/Unspoken/master/UnspokenEst_3.0.R")

```


